name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ic
      - name: build production project
        run: npm run build:prod
  lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    needs: [start]
    steps:
      - uses: actions/checkout@v2
      - name: installing modules
        run: npm ic
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    needs: [start]
    steps:
      - uses: actions/checkout@v2
      - name: installing modules
        run: npm ic
      - name: unit testing
        run: npm run test:unit
  storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    needs: [start]
    steps:
      - uses: actions/checkout@v2
      - name: installing modules
        run: npm ic
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci
